app = "halal-compliance-api"
primary_region = "iad"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8000"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[mounts]
  source = "halal_data"
  destination = "/app/results"
  persistent = true

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 4096
