services:
  - type: web
    name: halal-compliance-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app/main.py
    envVars:
      - key: PORT
        value: 8000
      - key: PYTHONPATH
        value: .
  - type: web
    name: halal-compliance-frontend
    env: static
    buildCommand: echo "Static files ready"
    staticPublishPath: ./frontend/static
    headers:
      - path: /*
        name: Access-Control-Allow-Origin
        value: "*"
      - path: /*
        name: Cache-Control
        value: no-cache
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: VITE_API_URL
        value: https://halal-compliance-api.onrender.com
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
    autoDeploy: true
