services:
  - type: web
    name: halal-compliance-api
    env: python
    buildCommand: |
      python -m pip install --upgrade pip
      pip install -r app/requirements.txt
      mkdir -p app/results/visualizations
      chmod -R 777 app/results
    startCommand: cd app && uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PORT
        value: 8000
      - key: PYTHONPATH
        value: ./app
      - key: CORS_ORIGINS
        value: "*"

  - type: static
    name: halal-compliance-frontend
    buildCommand: |
      cd frontend
      npm install
      npm run build
    staticPublishPath: ./frontend/dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: VITE_API_URL
        value: "https://halal-compliance-api.onrender.com"
