services:
  - type: web
    name: halal-compliance-api
    env: python
    buildCommand: |
      python -m pip install --upgrade pip
      pip install -r app/requirements.txt
      mkdir -p app/results/visualizations/slaughterhouse/2d
      mkdir -p app/results/visualizations/slaughterhouse/3d
      mkdir -p app/results/visualizations/food_processing/2d
      mkdir -p app/results/visualizations/food_processing/3d
      chmod -R 777 app/results
    startCommand: cd app && PYTHONPATH=/app uvicorn halal_compliance_api.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PORT
        value: 8000
      - key: PYTHONPATH
        value: ./app
      - key: CORS_ORIGINS
        value: "*"
      - key: MPLBACKEND
        value: "Agg"
    routes:
      - type: rewrite
        source: /api/*
        destination: /api/$1
      - type: rewrite
        source: /*
        destination: /

  - type: static
    name: halal-compliance-frontend
    buildCommand: |
      cd frontend
      npm install
      npm run build
    staticPublishPath: ./frontend/dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    headers:
      - path: /*
        name: Access-Control-Allow-Origin
        value: "*"
      - path: /*
        name: Cache-Control
        value: no-cache
      - path: /*
        name: X-Frame-Options
        value: ALLOWALL
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: VITE_API_URL
        value: "https://halal-compliance-api.onrender.com/api"
    pullRequestPreviewsEnabled: true
    autoDeploy: true
