services:
  - type: web
    name: halal-compliance-backend
    env: python
    buildCommand: cd backend && pip install -r requirements.txt
    startCommand: cd backend && python -m uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0

  - type: static
    name: halal-compliance-frontend
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/static
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
