services:
  - type: web
    name: halal-compliance-backend
    env: docker
    dockerfilePath: backend/Dockerfile
    buildCommand: ""
    startCommand: ""
    envVars:
      - key: PORT
        value: 8000

  - type: static
    name: halal-compliance-frontend
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/dist
    headers:
      - path: /*
        name: Access-Control-Allow-Origin
        value: "*"
      - path: /*
        name: Cache-Control
        value: no-cache
