services:
  - type: web
    name: halal-compliance-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app/main.py
    envVars:
      - key: PORT
        value: 8000
      - key: PYTHONPATH
        value: .
  - type: static
    name: halal-compliance-frontend
    env: static
    buildCommand: |
      cd frontend
      npm install
      npm run build
    staticPublishPath: frontend/dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: VITE_API_URL
        value: https://halal-compliance-api.onrender.com
      - key: PYTHONPATH
        value: .
    autoDeploy: true
