services:
  - type: web
    name: halal-compliance-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn halal_compliance_backend.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: PYTHONPATH
        value: /app
    autoDeploy: true
